name: prac-action
on: workflow_dispatch

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print text
        run: echo "hello world"

      - name: Print more text
        run: echo "hello again"
